<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="MusicRecordsRESTTests\**" />
    <Content Remove="MusicRecordsRESTTests\**" />
    <EmbeddedResource Remove="MusicRecordsRESTTests\**" />
    <None Remove="MusicRecordsRESTTests\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

</Project>
